version: '2'
services:
  mongodb:
    build: mongodb
    ports:
     - "27017:27017"
    container_name: "mymongodb"

  daemon:
    build: reddit_daemon
    depends_on:
     - mongodb
    links:
     - mongodb
    container_name: "mydaemon"

  web_server:
    build: web_server
    depends_on:
     - mongodb
    ports:
     - "5000:5000"
    links:
      - mongodb
    container_name: "mywebserver"
